// Achievement badge catalog. Pure metadata: the awarding engine maps badge ids
// to counter queries in code, and the artwork lives at public/badges/<id>.svg
// (tier and locked variants are generated by scripts/generate-badge-variants.mjs).

export type BadgeCategory = 'drep' | 'spo' | 'cc' | 'proposer' | 'forum' | 'crossover';

export interface Badge {
  /** Stable id; equals the artwork filename public/badges/<id>.svg. */
  id: string;
  name: string;
  /** Plain-language criterion shown on /badges and in galleries. */
  description: string;
  category: BadgeCategory;
  /** Hidden badges render as the mystery card until earned. */
  hidden?: boolean;
  /** Bronze / silver / gold thresholds; absent for single-award badges. */
  tiers?: [number, number, number];
  /** Progress goal of a single-award badge when it is more than 1. */
  goal?: number;
}

// Indexed by the badge_awards.tier value: 0 = untiered single award, 1..3 = bronze/silver/gold.
export const TIER_SLUGS = ['', 'bronze', 'silver', 'gold'] as const;

export const BADGE_CATEGORY_LABELS: Record<BadgeCategory, string> = {
  drep: 'DReps',
  spo: 'Stake pool operators',
  cc: 'Constitutional committee',
  proposer: 'Proposers',
  forum: 'Forum',
  crossover: 'Forum and chain',
};

export const BADGES: Badge[] = [
  // DRep, on-chain
  { id: 'first-vote', name: 'First Vote', description: 'Cast your first on-chain vote.', category: 'drep' },
  { id: 'active-voice', name: 'Active Voice', description: 'Cast 10 / 50 / 150 on-chain votes.', category: 'drep', tiers: [10, 50, 150] },
  { id: 'shows-the-work', name: 'Shows the Work', description: 'Cast 10 / 50 / 150 votes with a rationale anchor.', category: 'drep', tiers: [10, 50, 150] },
  { id: 'iron-streak', name: 'Iron Streak', description: 'Vote on every votable action for 6 / 18 / 73 consecutive epochs.', category: 'drep', tiers: [6, 18, 73] },
  { id: 'full-spectrum', name: 'Full Spectrum', description: 'Vote on all 7 governance action types.', category: 'drep', goal: 7 },
  { id: 'constitution-voter', name: 'Constitution Voter', description: 'Vote on a constitution update.', category: 'drep' },
  { id: 'hard-fork-voter', name: 'Hard Fork Voter', description: 'Vote on a hard fork initiation.', category: 'drep' },
  { id: 'genesis-drep', name: 'Genesis DRep', description: 'Registered as a DRep before epoch 520.', category: 'drep' },
  { id: 'veteran', name: 'Veteran', description: 'Registered for a full year and still active.', category: 'drep' },
  { id: 'identified', name: 'Identified', description: 'Complete CIP-119 profile: name, bio, image, and a link.', category: 'drep' },
  // Stake pool operators
  { id: 'pool-voice', name: 'Pool Voice', description: 'Cast 3 / 8 / 15 votes as a stake pool operator.', category: 'spo', tiers: [3, 8, 15] },
  { id: 'hard-fork-ready', name: 'Hard Fork Ready', description: 'Vote on a hard fork initiation as a stake pool operator.', category: 'spo' },
  // Constitutional committee
  { id: 'guardian', name: 'Guardian', description: 'Cast your first vote as a constitutional committee member.', category: 'cc' },
  { id: 'reasoned-guardian', name: 'Reasoned Guardian', description: 'Cast 10 committee votes with a rationale anchor.', category: 'cc', goal: 10 },
  // Proposers
  { id: 'proposer', name: 'Proposer', description: 'Submit your first governance action.', category: 'proposer' },
  { id: 'serial-proposer', name: 'Serial Proposer', description: 'Submit 5 governance actions.', category: 'proposer', goal: 5 },
  { id: 'enacted', name: 'Enacted', description: 'A governance action you submitted was ratified or enacted.', category: 'proposer' },
  // Forum
  { id: 'hello-governance', name: 'Hello Governance', description: 'Write your first post.', category: 'forum' },
  { id: 'opening-move', name: 'Opening Move', description: 'Start your first topic.', category: 'forum' },
  { id: 'regular', name: 'Regular', description: 'Write 10 / 50 / 250 posts.', category: 'forum', tiers: [10, 50, 250] },
  { id: 'well-said', name: 'Well Said', description: 'Receive 10 / 50 / 200 thumbs up on your posts.', category: 'forum', tiers: [10, 50, 200] },
  { id: 'crowd-favorite', name: 'Crowd Favorite', description: 'A single post receives 10 thumbs up.', category: 'forum', goal: 10 },
  { id: 'sparked-a-debate', name: 'Sparked a Debate', description: 'A topic you started receives 5 replies from others.', category: 'forum', goal: 5 },
  { id: 'forum-streak', name: 'Forum Streak', description: 'Post in 6 / 18 / 73 consecutive epochs.', category: 'forum', tiers: [6, 18, 73] },
  { id: 'on-the-record', name: 'On the Record', description: 'Post in 5 / 25 / 75 different governance action threads.', category: 'forum', tiers: [5, 25, 75] },
  // Forum and chain
  { id: 'says-and-does', name: 'Says and Does', description: 'Discuss and vote on the same governance action, 5 / 25 / 75 times.', category: 'crossover', tiers: [5, 25, 75] },
  { id: 'open-book', name: 'Open Book', description: 'Provide a vote rationale and join the thread on 10 actions.', category: 'crossover', goal: 10 },
  { id: 'deliberator', name: 'Deliberator', description: 'Post in the thread before casting your vote, 10 times.', category: 'crossover', goal: 10 },
  // Hidden: shown as the mystery card until earned, descriptions revealed after
  { id: 'lone-voice', name: 'Lone Voice', description: 'Voted against more than 90% of the voted stake on a decided action.', category: 'drep', hidden: true },
  { id: 'steady-hand', name: 'Steady Hand', description: 'Voted on a motion of no confidence.', category: 'drep', hidden: true },
  { id: 'triple-crown', name: 'Triple Crown', description: 'Three verified on-chain roles on one account.', category: 'forum', hidden: true },
  { id: 'buzzer-beater', name: 'Buzzer Beater', description: 'Voted in an action\'s final epoch before it expired.', category: 'drep', hidden: true },
  { id: 'early-bird', name: 'Early Bird', description: 'Voted in the same epoch the action was submitted.', category: 'drep', hidden: true },
  { id: 'necromancer', name: 'Necromancer', description: 'Revived a topic dormant for over 60 days.', category: 'forum', hidden: true },
  { id: 'century-thread', name: 'Century Thread', description: 'Posted in a topic that reached 100 posts.', category: 'forum', hidden: true },
  { id: 'boundary-rider', name: 'Boundary Rider', description: 'Posted within 10 minutes of an epoch boundary.', category: 'forum', hidden: true },
  { id: 'collector', name: 'Collector', description: 'Earned every visible forum badge.', category: 'forum', hidden: true },
];

const BADGES_BY_ID = new Map(BADGES.map((b) => [b.id, b]));

export function getBadge(id: string): Badge | undefined {
  return BADGES_BY_ID.get(id);
}

export const VISIBLE_BADGES: readonly Badge[] = BADGES.filter((b) => !b.hidden);
export const HIDDEN_BADGES: readonly Badge[] = BADGES.filter((b) => b.hidden);

/** Artwork URL for a badge at a given award tier (0 or absent = the base file). */
export function badgeImagePath(id: string, tier = 0): string {
  const slug = TIER_SLUGS[tier] ?? '';
  return slug ? `/badges/${id}-${slug}.svg` : `/badges/${id}.svg`;
}

/** Artwork URL for a not-yet-earned badge (mystery card when hidden). */
export function badgeLockedImagePath(badge: Badge): string {
  return badge.hidden ? '/badges/mystery.svg' : `/badges/${badge.id}-locked.svg`;
}
